super_sponge:
  radius: 20
  #Absorption shapes: DIAMOND, CUBE, SPHERE | the default is DIAMOND (doesn't have to be all caps btw)
  absorption_shape: CUBE
  #If the water should keep flowing after it was absorbed. (true = update blocks)
  #Blocks like coral won't be updated when the water is removed, resulting in them not being able to die.
  update_blocks: true
  absorb_interval_ticks: 1
  #How often to refresh the sponge tooltip in player inventories. (measured in ticks) Set 0 to disable.
  tooltip_refresh_interval_ticks: 1200
  replace_blocks:
    - WATER
    - BUBBLE_COLUMN
    - KELP
    - KELP_PLANT
    - SEAGRASS
    - TALL_SEAGRASS
    - GLOW_LICHEN
  item:
    name: "&dSuper Sponge"
    lore:
      - "&7Absorbs all water in a {radius} block radius."
  recipe:
    enabled: true
    shapeless: false
    shape:
      - "SSS"
      - "SNS"
      - "SSS"
    ingredients:
      S: SPONGE
      N: NETHER_STAR
